### ISSUE TITLE
Mobile support is broken

### ISSUE THREAD

**Issue by syedkarim** [Othernet-Project/RxOS-UI2#1]
## Expected behaviour
The UI should function without problems on small screens. Operating system and browser should have no impact on usability. 

## Actual behaviour
On Safari/iOS/iPhone 6S, the screen is completely locked. On Kindle/Silk, the screen is also frozen. There are many permutations of small screens/mobile OS/non-Firefox which prevents the user from interacting with Skylark. 

## Steps to reproduce the error
Open the following link on a device with a 4-inch screen and Chrome browser: 
http://kamots.homeip.net:61080/

## (Optinal) Browser and OS information
Firefox works better than the rest of the browsers.

**Comment by andersevenrud** [comment]
In the recent release both touch and scaling has been improved: http://community.os.js.org/t/update-version-bump-alpha85/ . If you want to test it, see: https://demo.os-js.org/ .

The next plan is to iron out all input stuff (based on feedback) and then refine some UI elements to make better use of space.

**Comment by jmig5776** [comment]
I would like to work upon this. Can you tell me where do you think the problem is occurring for screen frozen as it will be helpful to me.

**Comment by andersevenrud** [comment]
It's been so long that I can't remember exactly what the issue was. But if you dig into the alpha85 release of v2 you might get some pointers. I'm guessing it has something to do with the input handler (`events.js` utils file).

v2.x is deprecated, but it's still on github if you dig in the history: https://github.com/os-js/OS.js/tree/master (v2.1 is the master branch HEAD, and v3 branch is the latest active which is not backward compatible).

Speaking of v3 I actually started on a conversion: https://github.com/andersevenrud/RxOS-UI3 -- This version is better optimized for mobile devices etc.

**Comment by jmig5776** [comment]
> It's been so long that I can't remember exactly what the issue was.

Is this issue is still open for bounty? If not then please be clear because i have some finance situation here.
>  I'm guessing it has something to do with the input handler (events.js utils file).

Yeah I was looking up the code so far.

**Comment by andersevenrud** [comment]
> Is this issue is still open for bounty? If not then please be clear because i have some finance situation here.

I don't know anything about that. I'm the creator of OS.js, not a part of the Outernet organization.

**Comment by jmig5776** [comment]
> I don't know anything about that. I'm the creator of OS.js, not a part of the Outernet organization.

Ohh than please don't mind.

**Comment by syedkarim** [comment]
This bounty is quite old and has already been resolved. Please do not spend any time on this. I will close the bounty shortly.

**Comment by jmig5776** [comment]
Thanks @syedkarim for making it clear.

**Comment by syedkarim** [comment]
I've submitted an email to BountySource to close the bounty.

**Comment by syedkarim** [comment]
Closing this issue as it is no longer relevant.
