### ISSUE TITLE
I donto know how to use this device plz help[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by kashifmoin** [Othernet-Project/RxOS-UI2#6]
**This bugreport was generated by Outernet Skylark:**

> An error occured while trying to launch: ApplicationTuner

> Application 'ApplicationTuner' preloading failed: 
/packages/default/Tuner/scheme.html

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko"}
```

**Comment by abgoyal** [comment]
Please do NOT use github issues for technical support. Goto the forums on http://forums.outernet.is
